server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sky_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sport.pojo.entity
  #开启数据库命名与Java驼峰命名的转换
  configuration:
    map-underscore-to-camel-case: true

sport:
  jwt:
    admin-secret-key: sportSGT
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: sportXE
    user-ttl: 7200000
    uer-token-name: authentication
