server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: ${sport.datasource.driver-class-name}
      url: jdbc:mysql://${sport.datasource.host}:${sport.datasource.port}/${sport.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sport.datasource.username}
      password: ${sport.datasource.password}



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sport.pojo.entity
  #开启数据库命名与Java驼峰命名的转换
  configuration:
    map-underscore-to-camel-case: true

sport:
  jwt:
    admin-secret-key: sportSGT
    admin-ttl: 7200000
    admin-token-name: adminToken
    user-secret-key: sportXE
    user-ttl: 7200000
    uer-token-name: token

#输出日志
logging:
  level:
    com:
      sport:
        mapper: debug
        service: info
        controller: info